include:
  - docker-compose.pulsar.yml
services:
  program-service-db:
    image: postgres:16
    environment:
      POSTGRES_DB: alpespartners
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres_user -d alpespartners -h 127.0.0.1"]
      interval: 3s
      timeout: 3s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
  program-service:
    build: 
      context: .
      dockerfile: ./Dockerfile   
    ports:
      - "5000:5000"
    environment:
      POSTGRES_DB: alpespartners
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: 1234
      POSTGRES_HOST: program-service-db
      POSTGRES_PORT: 5432
      BROKER_URL: pulsar://broker:6650
    depends_on:
      program-service-db:
        condition: service_healthy
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
  compliance-network:
    driver: bridge
