# Default values for partners-bff
# This is a YAML-formatted file.

replicaCount: 2

image:
  repository: us-east1-docker.pkg.dev/misw4406-2025-14-desacopla2/partners-bff/partners-bff
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations:
    iam.gke.io/gcp-service-account: "app-sa@misw4406-2025-14-desacopla2.iam.gserviceaccount.com"
  # The name of the service account to use.
  name: "app-sa"

podAnnotations: {}

podSecurityContext:
  fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: NodePort
  port: 80
  targetPort: 8000

ingress:
  enabled: true
  className: "gce"
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: "partners-bff-api-ip"
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: partners-bff-tls
  #    hosts:
  #      - partners-bff.local

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Broker configuration
broker:
  url: "pulsar://pulsar-broker.pulsar.svc.cluster.local:6650"

# Secrets configuration
secrets: {}

# Environment variables
env:
  - name: APP_NAME
    value: "Partners BFF app"
  - name: LOG_LEVEL
    value: "INFO"

# Health check configuration
healthCheck:
  enabled: true
  path: /posts/ping
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

# Liveness probe configuration
livenessProbe:
  enabled: true
  path: /posts/ping
  initialDelaySeconds: 60
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 3

# Readiness probe configuration
readinessProbe:
  enabled: true
  path: /posts/ping
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3