# Default values for integrations-service
# This is a YAML-formatted file.

replicaCount: 2

image:
  repository: us-east1-docker.pkg.dev/misw4406-2025-14-desacopla2/integrations-service/integrations-service
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations:
    iam.gke.io/gcp-service-account: "app-sa@misw4406-2025-14-desacopla2.iam.gserviceaccount.com"
  # The name of the service account to use.
  name: "app-sa"

podAnnotations: {}

podSecurityContext:
  fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: NodePort
  port: 80
  targetPort: 5001

ingress:
  enabled: false
  className: "gce"
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: "integrations-service-ip"
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: integrations-service-tls
  #    hosts:
  #      - integrations-service.local

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Database configuration
database:
  host: "10.179.0.5"
  port: 5432
  name: "integrations_database"
  user: "integrations_user"
  sslMode: "require"

# Broker configuration
broker:
  url: "pulsar://pulsar-broker.pulsar.svc.cluster.local:6650"

# Secrets configuration
secrets:
  # integrations_password -> integrations password
  postgresPassword: "aW50ZWdyYXRpb25zX3Bhc3N3b3Jk"

# Environment variables
env:
  - name: SQLALCHEMY_DATABASE_URI
    valueFrom:
      configMapKeyRef:
        name: integrations-service-config
        key: SQLALCHEMY_DATABASE_URI
  - name: BROKER_URL
    valueFrom:
      configMapKeyRef:
        name: integrations-service-config
        key: BROKER_URL

# Health check configuration
healthCheck:
  enabled: true
  path: /health
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

# Liveness probe configuration
livenessProbe:
  enabled: true
  path: /health
  initialDelaySeconds: 60
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 3

# Readiness probe configuration
readinessProbe:
  enabled: true
  path: /health
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
