# Default values for campaigns-service
# This is a YAML-formatted file.

replicaCount: 2

image:
  repository: us-east1-docker.pkg.dev/misw4406-2025-14-desacopla2/campaigns-service/campaigns-service
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations:
    iam.gke.io/gcp-service-account: "app-sa@misw4406-2025-14-desacopla2.iam.gserviceaccount.com"
  # The name of the service account to use.
  name: "app-sa"

podAnnotations: {}

podSecurityContext:
  fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: NodePort
  port: 80
  targetPort: 5000

ingress:
  enabled: true
  className: "gce"
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: "campaigns-service-ip"
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: campaigns-service-tls
  #    hosts:
  #      - campaigns-service.local

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Database configuration
database:
  host: "10.179.0.3"
  port: 5432
  name: "campaigns_database"
  user: "campaigns_user"
  sslMode: "require"

# Broker configuration
broker:
  url: "pulsar://pulsar-broker.pulsar.svc.cluster.local:6650"

# Secrets configuration
secrets:
  # Y2hhbmdlbWU= -> campaigns password
  postgresPassword: "WTJoaGJtZGxiV1U9"

# Environment variables
env:
  - name: POSTGRES_HOST
    valueFrom:
      configMapKeyRef:
        name: campaigns-service-config
        key: POSTGRES_HOST
  - name: POSTGRES_PORT
    valueFrom:
      configMapKeyRef:
        name: campaigns-service-config
        key: POSTGRES_PORT
  - name: POSTGRES_DB
    valueFrom:
      configMapKeyRef:
        name: campaigns-service-config
        key: POSTGRES_DB
  - name: POSTGRES_USER
    valueFrom:
      configMapKeyRef:
        name: campaigns-service-config
        key: POSTGRES_USER
  - name: POSTGRES_PASSWORD
    valueFrom:
      secretKeyRef:
        name: campaigns-service-secrets
        key: POSTGRES_PASSWORD
  - name: BROKER_URL
    valueFrom:
      configMapKeyRef:
        name: campaigns-service-config
        key: BROKER_URL

# Health check configuration
healthCheck:
  enabled: true
  path: /health
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

# Liveness probe configuration
livenessProbe:
  enabled: true
  path: /health
  initialDelaySeconds: 60
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 3

# Readiness probe configuration
readinessProbe:
  enabled: true
  path: /health
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
