apiVersion: v1
kind: Secret
metadata:
  name: {{ include "integrations-service.fullname" . }}-secrets
  labels:
    {{- include "integrations-service.labels" . | nindent 4 }}
type: Opaque
data:
  # Base64 encoded database password
  # Use: echo -n "your-password" | base64
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | default "REPLACE_WITH_BASE64_ENCODED_PASSWORD" | quote }}
