# Pulsar Helm Chart Values
# Basic configuration for development/testing

# Enable components
components:
  zookeeper: true
  bookkeeper: true
  broker: true
  proxy: true
  functions: false
  toolset: true
  pulsar_manager: true

# Zookeeper configuration (minimum for single node)
zookeeper:
  replicaCount: 1
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "100m"

# BookKeeper configuration (minimum for single node)
bookkeeper:
  replicaCount: 1
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "200m"

# Broker configuration (minimum for single node)
broker:
  replicaCount: 1
  resources:
    requests:
      memory: "512Mi"
      cpu: "200m"
    limits:
      memory: "1Gi"
      cpu: "500m"

# Proxy configuration (minimum for single node)
proxy:
  replicaCount: 1
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "200m"

# Functions worker configuration (disabled for cost savings)
functions:
  replicaCount: 0

# Toolset configuration (minimum)
toolset:
  replicaCount: 1
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "100m"

# Pulsar Manager configuration (web UI)
pulsar_manager:
  replicaCount: 1
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "200m"
  service:
    type: ClusterIP
    port: 9527

# Storage configuration
volumes:
  persistence: true
  storageClassName: "standard-rwo"

# Service configuration
service:
  type: ClusterIP
  ports:
    http: 8080
    pulsar: 6650
