apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "partners-bff.fullname" . }}-config
  labels:
    {{- include "partners-bff.labels" . | nindent 4 }}
data:
  BROKER_URL: {{ .Values.broker.url | quote }}
