
services:
  # PostgreSQL database for saga state persistence
  postgres:
    image: postgres:15-alpine
    container_name: saga-postgres
    environment:
      POSTGRES_DB: saga_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - saga-network

  # Apache Pulsar for event messaging
  pulsar:
    image: apachepulsar/pulsar:3.1.0
    container_name: saga-pulsar
    command: bin/pulsar standalone
    ports:
      - "6650:6650"  # Pulsar broker
      - "8081:8080"  # Pulsar admin (changed to avoid conflict)
    environment:
      - PULSAR_MEM=-Xms512m -Xmx512m -XX:MaxDirectMemorySize=256m
    volumes:
      - pulsar_data:/pulsar/data
    healthcheck:
      test: ["CMD", "bin/pulsar-admin", "brokers", "healthcheck", "--admin-url", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - saga-network

  # Saga Orchestrator Service
  saga-orchestrator:
    build: .
    container_name: saga-orchestrator
    ports:
      - "5003:5003"
    environment:
      - BROKER_URL=pulsar://pulsar:6650
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/saga_db
      - INTEGRACIONES_API_URL=http://gestion-de-integraciones:5001
      - ALIANZAS_API_URL=http://gestion-de-alianzas:5002
      - HOST=0.0.0.0
      - PORT=5003
      - DEBUG=false
    depends_on:
      postgres:
        condition: service_healthy
      pulsar:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5003/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - saga-network
    restart: unless-stopped

  # Gestion de Integraciones (if you want to run it locally)
  gestion-de-integraciones:
    build: ../gestion-de-integraciones
    container_name: gestion-de-integraciones
    ports:
      - "5001:5001"
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:postgres@postgres:5432/partners_db
      - BROKER_URL=pulsar://pulsar:6650
      - SAGA_ORCHESTRATOR_URL=http://saga-orchestrator:5003
    depends_on:
      postgres:
        condition: service_healthy
      pulsar:
        condition: service_healthy
    networks:
      - saga-network
    restart: unless-stopped

  # Gestion de Alianzas (if you want to run it locally)
  gestion-de-alianzas:
    build: ../gestion-de-alianzas
    container_name: gestion-de-alianzas
    ports:
      - "5002:5002"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/alianzas_db
      - BROKER_URL=pulsar://pulsar:6650
    depends_on:
      postgres:
        condition: service_healthy
      pulsar:
        condition: service_healthy
    networks:
      - saga-network
    restart: unless-stopped

  # Pulsar Manager (Optional - for UI management)
  pulsar-manager:
    image: apachepulsar/pulsar-manager:v0.3.0
    container_name: saga-pulsar-manager
    ports:
      - "9527:9527"
      - "7750:7750"
    environment:
      - SPRING_CONFIGURATION_FILE=/pulsar-manager/pulsar-manager/application.properties
    depends_on:
      - pulsar
    networks:
      - saga-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  pulsar_data:
    driver: local

networks:
  saga-network:
    driver: bridge
